language: ruby
sudo: false
rvm:
  - 2.6.5
  - 2.7.0
  - 3.0.0

gemfile:
  - gemfiles/activesupport_2.3_LTS.gemfile
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfile
  - gemfiles/activesupport_5.gemfile
  - gemfiles/activesupport_6.gemfile
  - gemfiles/activesupport_7.gemfile

jobs:
  exclude:
  - rvm: 2.7.0
    gemfile: gemfiles/activesupport_3.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/activesupport_4.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/activesupport_3.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/activesupport_4.gemfile

before_install:
  - yes | gem update --system --force
  - gem install bundler
